#!/usr/bin/expect -f
spawn /download/$env(mudletVersion)
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Press \[Enter\] to continue\:"
send -- "\n"
expect "Do you accept this license? \[y\/n\]\:"
expect "Press \[Enter\] to continue\:"
send -- "y\n"
expect "Installation Directory \[/opt/mudlet-3.0.0-delta\]\:"
send -- "\/opt\/mudlet\n"
expect "Do you want to continue? \[Y\/n\]\:"
send -- "y\n"
expect "Setup has finished installing Mudlet on your computer."
interact
